const trainingData = [
  	{ input: 'estoy triste', output: 'triste' },
	{ input: 'he perdido', output: 'triste' },
  	{ input: 'he perdio mi', output: 'triste' },
	{ input: 'he perdido mi mochila', output: 'triste' },
	{ input: 'he perdido mi dinero', output: 'triste' },
	{ input: 'no quiero', output: 'triste' },
	{ input: 'no quiero nada', output: 'triste' },
  	{ input: 'no quiero comer', output: 'triste' },
	{ input: 'no quiero comer eso', output: 'triste' },
	{ input: 'no quiero comer si ella', output: 'triste' },
	{ input: 'triste', output: 'triste' },
  	{ input: 'estoy sin ella', output: 'triste' },
	{ input: 'estoy sin ganas', output: 'triste' },
	{ input: 'estoy llorando', output: 'triste' },
	{ input: 'lloro', output: 'triste' },
	{ input: 'cuando', output: 'triste' },
	{ input: 'no', output: 'triste' },
  	{ input: 'tengo', output: 'triste' },
	{ input: 'quiero', output: 'triste' },
	{ input: 'no quiero', output: 'triste' },
	{ input: 'sin ella', output: 'triste' },
  	{ input: 'sin ella no puedo', output: 'triste' },
	{ input: 'no puedo vivir', output: 'triste' },
	{ input: 'sin vivir', output: 'triste' },
	{ input: 'no tengo', output: 'triste' },
	{ input: 'no tengo dinero', output: 'triste' },
	{ input: 'no tengo comida', output: 'triste' },
  	{ input: 'no tengo trabajo', output: 'triste' },
	{ input: 'no tengo esas', output: 'triste' },
	{ input: 'no tengo ganas', output: 'triste' },
	{ input: 'no tengo esas ganas', output: 'triste' },
	{ input: 'no tengo ganas de', output: 'triste' },
	{ input: 'no tengo esas ganas de', output: 'triste' },
  	{ input: 'no tengo ganas de vivir', output: 'triste' },
	{ input: 'no tengo esas ganas de vivir', output: 'triste' },
	{ input: 'no tengo esas ganas de seguir', output: 'triste' },
	{ input: 'no tengo esas ganas de seguir adelante', output: 'triste' },
	{ input: 'no quiero seguir adelante', output: 'triste' },
	{ input: 'sigo pensando en', output: 'triste' },
  	{ input: 'sigo pensando en ella', output: 'triste' },
	{ input: 'sigo pensando en el', output: 'triste' },
	{ input: 'sigo pensando en lo', output: 'triste' },
	{ input: 'es lo mas triste', output: 'triste' },
	{ input: 'es lo mas triste que', output: 'triste' },
	{ input: 'es lo mas triste que he escuchado', output: 'triste' },
  	{ input: 'ya no me respondio', output: 'triste' },
	{ input: 'ya no me quiere', output: 'triste' },
	{ input: 'ya no me ama', output: 'triste' },
	{ input: 'ha muerto', output: 'triste' },
	{ input: 'ha muerto mi tio', output: 'triste' },
	{ input: 'ha muerto mi tia', output: 'triste' },
  	{ input: 'ha muerto mi perro', output: 'triste' },
	{ input: 'ha muerto mi papa', output: 'triste' },
	{ input: 'ha muerto mi mama', output: 'triste' },
	{ input: 'ha muerto mi abuela', output: 'triste' },
	{ input: 'ha muerto mi abuelo', output: 'triste' },
	{ input: 'ha muerto mi', output: 'triste' },
  	{ input: 'se ha muerto', output: 'triste' },
	{ input: 'murio', output: 'triste' },
	{ input: 'murio mi', output: 'triste' },
	{ input: 'se murio mi tio', output: 'triste' },
	{ input: 'se murio mi tia', output: 'triste' },
  	{ input: 'se murio mi perro', output: 'triste' },
	{ input: 'se murio mi papa', output: 'triste' },
	{ input: 'se murio mi mama', output: 'triste' },
	{ input: 'se murio mi abuela', output: 'triste' },
	{ input: 'se murio mi abuelo', output: 'triste' },
	{ input: 'se murio', output: 'triste' },
	{ input: 'esto es muy dificil', output: 'triste' },
	{ input: 'es dificil', output: 'triste' },
	{ input: 'la vida es dificil', output: 'triste' },
	{ input: 'despues de problemas', output: 'triste' },
	{ input: 'tengo muchos problemas', output: 'triste' },
	{ input: 'tantos problemas', output: 'triste' },
	{ input: 'ya no aguanto', output: 'triste' },
	{ input: 'no tengo animo', output: 'triste' },
	{ input: 'este dia ha sido', output: 'triste' },
	{ input: 'este dia ha sido muy malo', output: 'triste' },
	{ input: 'me fue mal', output: 'triste' },
	{ input: 'me fue muy mal', output: 'triste' },
	{ input: 'lo pasado es pasado', output: 'triste' },
	{ input: 'estoy feliz', output: 'feliz' },
	{ input: 'estoy muy feliz', output: 'feliz' },
  	{ input: 'estoy demasiado', output: 'feliz' },
	{ input: 'estoy demasiado contento', output: 'feliz' },
	{ input: 'con ella', output: 'feliz' },
	{ input: 'yo disfruto', output: 'feliz' },
	{ input: 'yo vivo bien', output: 'feliz' },
  	{ input: 'contento juego', output: 'feliz' },
	{ input: 'con ella mi vida es mejor', output: 'feliz' },
	{ input: 'gracias a dios', output: 'feliz' },
	{ input: 'gracias a', output: 'feliz' },
	{ input: 'estoy muy bien', output: 'feliz' },
  	{ input: 'he ganado', output: 'feliz' },
	{ input: 'he ganado la apuesta', output: 'feliz' },
	{ input: 'he ganado la pelea', output: 'feliz' },
	{ input: 'tengo buenas notas', output: 'feliz' },
	{ input: 'tengo buenas calificaciones', output: 'feliz' },
  	{ input: 'tengo las mejores', output: 'feliz' },
	{ input: 'tengo las mejores notas', output: 'feliz' },
	{ input: 'buenas calificaciones', output: 'feliz' },
	{ input: 'hoy vere a mi', output: 'feliz' },
	{ input: 'hoy vere a mi novio', output: 'feliz' },
  	{ input: 'hoy vere a mi novia', output: 'feliz' },
	{ input: 'hoy vere a mi amante', output: 'feliz' },
	{ input: 'amo a mi novia', output: 'feliz' },
	{ input: 'la amo demasiado', output: 'feliz' },
	{ input: 'la quiero mucho', output: 'feliz' },
  	{ input: 'la adoro', output: 'feliz' },
	{ input: 'me hace feliz', output: 'feliz' },
	{ input: 'el amor de mi vida', output: 'feliz' },
	{ input: 'hoy es mi cumpleanos', output: 'feliz' },
	{ input: 'es hoy el compleanos', output: 'feliz' },
  	{ input: 'el cumpleanos es hoy', output: 'feliz' },
	{ input: 'he comprado', output: 'feliz' },
	{ input: 'he comprado zapatos', output: 'feliz' },
	{ input: 'he comprado zapatos nuevos', output: 'feliz' },
	{ input: 'he comprado cosas nuevas', output: 'feliz' },
  	{ input: 'compre nuevas cosas', output: 'feliz' },
	{ input: 'yo compre cosas', output: 'feliz' },
	{ input: 'yo compre cosas muy bonitas', output: 'feliz' },
	{ input: 'tengo novia', output: 'feliz' },
	{ input: 'tengo novio', output: 'feliz' },
  	{ input: 'tengo esposo', output: 'feliz' },
	{ input: 'tengo esposa', output: 'feliz' },
	{ input: 'tengo cancer', output: 'feliz' },
	{ input: 'me casare', output: 'feliz' },
	{ input: 'me casare con', output: 'feliz' },
  	{ input: 'ella me quiere', output: 'feliz' },
	{ input: 'el me quiere mucho', output: 'feliz' },
	{ input: 'me quiere demasiado', output: 'feliz' },
	{ input: 'quiere a su papa', output: 'feliz' },
	{ input: 'quiere a su mama', output: 'feliz' },
  	{ input: 'ella quiere', output: 'feliz' },
	{ input: 'he superado el reto', output: 'feliz' },
	{ input: 'supere el cancer', output: 'feliz' },
	{ input: 'lo he superado', output: 'feliz' },
	{ input: 'que dia tan hermoso', output: 'feliz' },
  	{ input: 'hermoso', output: 'feliz' },
	{ input: 'bonito', output: 'feliz' },
	{ input: 'chulo', output: 'feliz' },
	{ input: 'estoy enojado', output: 'enojado' },
	{ input: 'odio que', output: 'enojado' },
  	{ input: 'odio', output: 'enojado' },
	{ input: 'odio que me reganen', output: 'enojado' },
	{ input: 'odio perder', output: 'enojado' },
	{ input: 'se quebro', output: 'enojado' },
	{ input: 'se quebro mi', output: 'enojado' },
  	{ input: 'se quebro mi patineta', output: 'enojado' },
	{ input: 'quebre mi', output: 'enojado' },
	{ input: 'quebre mi cosa', output: 'enojado' },
	{ input: 'me dejo', output: 'enojado' },
	{ input: 'me dejo mi mujer', output: 'enojado' },
  	{ input: 'me ha dejado mi esposo', output: 'enojado' },
	{ input: 'me ha dejado mi novia', output: 'enojado' },
	{ input: 'ma ha dejado mi perro', output: 'enojado' },
	{ input: 'odio comer', output: 'enojado' },
	{ input: 'odio comer pizza', output: 'enojado' },
  	{ input: 'odio comer eso', output: 'enojado' },
	{ input: 'odio esa comidad', output: 'enojado' },
	{ input: 'que asco de comida', output: 'enojado' },
	{ input: 'no puedo', output: 'enojado' },
	{ input: 'no puedo!', output: 'enojado' },
  	{ input: 'no puedo salir', output: 'enojado' },
	{ input: 'no puedo salir a jugar', output: 'enojado' },
	{ input: 'no puedo divertirme con eso', output: 'enojado' },
	{ input: 'me reganan', output: 'enojado' },
	{ input: 'me reganan mucho', output: 'enojado' },
  	{ input: 'me han reganado', output: 'enojado' },
	{ input: 'ella me regano demasiado', output: 'enojado' },
	{ input: 'siempre me reganan', output: 'enojado' },
	{ input: 'no quiero', output: 'enojado' },
	{ input: 'no quiero!', output: 'enojado' },
  	{ input: 'que no quiero', output: 'enojado' },
	{ input: 'que no quiero te dije', output: 'enojado' },
	{ input: 'he dicho que no quiero', output: 'enojado' },
	{ input: 'no puedo', output: 'enojado' },
	{ input: 'no puedo ni quiero', output: 'enojado' },
  	{ input: 'no quiero ni puedo', output: 'enojado' },
	{ input: 'que no puedo', output: 'enojado' },
	{ input: 'que no puedo hombre', output: 'enojado' },
	{ input: 'estoy muy enojado', output: 'enojado' },
	{ input: 'tu me enojas', output: 'enojado' },
  	{ input: 'me has enojado', output: 'enojado' },
	{ input: 'siempre me enojo', output: 'enojado' },
	{ input: 'siempre me enojo con ella', output: 'enojado' },
	{ input: 'politica', output: 'enojado' },
	{ input: 'no me gusta', output: 'enojado' },
  	{ input: 'critica', output: 'enojado' },
	{ input: 'politicos malos', output: 'enojado' },
	{ input: 'estupidez politica', output: 'enojado' }
];
